# Generated by Django 4.1.5 on 2023-01-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printprovider',
            old_name='user_name',
            new_name='phone_number',
        ),
    ]
