# Generated by Django 4.1.5 on 2023-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='phone_number2',
            new_name='phone_number',
        ),
    ]
