# Generated by Django 4.1.5 on 2023-01-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blank_product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('designer_id', models.IntegerField()),
                ('provider_id', models.IntegerField()),
                ('design_src', models.CharField(max_length=60)),
                ('sample_src', models.CharField(max_length=60)),
                ('discount_percent', models.IntegerField()),
                ('status', models.CharField(choices=[('DES', 'طراحی شده'), ('CON', 'تایید شده'), ('REJ', 'رد شده')], max_length=15)),
                ('is_available', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blank_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='blank_product.blankproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='blank_product.blankproducttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProviderProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('prep_time', models.CharField(max_length=20)),
                ('blank_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppp', to='blank_product.blankproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProviderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppd', to='product.color')),
                ('product_provider_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppd', to='product.productproviderprop')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppd', to='product.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=60)),
                ('is_preview', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='product.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='product.size')),
            ],
        ),
    ]
