# Generated by Django 4.1.5 on 2023-02-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproviderdetail',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productproviderdetail',
            name='product_provider_prop',
        ),
        migrations.RemoveField(
            model_name='productproviderdetail',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productproviderprop',
            name='blank_product',
        ),
        migrations.RemoveField(
            model_name='productproviderprop',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='size',
            name='type',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='utils.color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='utils.size'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ProductProviderDetail',
        ),
        migrations.DeleteModel(
            name='ProductProviderProp',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
