# Generated by Django 4.1.5 on 2023-02-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('blank_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProviderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductProviderProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.CharField(max_length=20)),
                ('blank_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppp', to='blank_product.blankproduct')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_provider_prop', to='account.printprovider')),
            ],
        ),
    ]
